backend:
  name: github
  repo: carlathomaspsicologa/carla-thomas-site
  branch: main

locale: pt

media_folder: src/assets/img/blog
public_folder: /assets/img/blog

collections:
  - name: blog
    label: Blog
    label_singular: Artigo
    folder: src/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - { label: Título, name: title, widget: string }
      - { label: Data, name: date, widget: datetime, date_format: "DD/MM/YYYY", time_format: false, format: "YYYY-MM-DD" }
      - { label: Resumo, name: resumo, widget: text }
      - { label: Imagem de capa, name: capa, widget: image, required: false }
      - { label: Conteúdo, name: body, widget: markdown }
